-- USUÁRIO
CREATE TABLE IF NOT EXISTS perfil (
                                             id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             descricao VARCHAR(255),
    CONSTRAINT pk_perfil PRIMARY KEY (id)
    );

-- Tabela usuario (usuários globais; sem FK direta pra cliente)
CREATE TABLE IF NOT EXISTS usuario (
                                              id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                              nome        VARCHAR(80),
    email       VARCHAR(255),
    senha       VARCHAR(255),
    cpf         VARCHAR(11),
    ativo       BOOLEAN,
    primeiro_acesso      BOOLEAN,
    dt_criacao  TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS usuario_perfil (
                                                     perfil_id  BIGINT NOT NULL,
                                                     usuario_id BIGINT NOT NULL,
                                                     CONSTRAINT pk_usuario_perfil PRIMARY KEY (perfil_id, usuario_id),
    CONSTRAINT fk_usuper_on_perfil  FOREIGN KEY (perfil_id)  REFERENCES perfil (id),
    CONSTRAINT fk_usuper_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
    );

-- Seeds de perfil (evita duplicar em reruns)
INSERT INTO perfil (descricao)
SELECT 'ADMIN'
    WHERE NOT EXISTS (SELECT 1 FROM perfil WHERE descricao = 'ADMIN');

INSERT INTO perfil (descricao)
SELECT 'USER'
    WHERE NOT EXISTS (SELECT 1 FROM perfil WHERE descricao = 'USER');
