-- V001__baseline_public.sql
-- Somente objetos globais (schema public). Nada de audit aqui.

-- Tabela cliente (catálogo global de tenants)
CREATE TABLE IF NOT EXISTS public.cliente (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome    VARCHAR(255),
    codigo  VARCHAR(255),
    schema  VARCHAR(255),
    descricao_empresa text,
    ativo boolean,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
    );

-- Tabela perfil (perfis globais)
CREATE TABLE IF NOT EXISTS public.perfil (
                                             id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             descricao VARCHAR(255),
    CONSTRAINT pk_perfil PRIMARY KEY (id)
    );

-- Tabela usuario (usuários globais; sem FK direta pra cliente)
CREATE TABLE IF NOT EXISTS public.usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(80),
    email       VARCHAR(255),
    senha       VARCHAR(255),
    cpf         VARCHAR(11),
    ativo       BOOLEAN,
    primeiro_acesso      BOOLEAN,
    dt_criacao  TIMESTAMP,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
    );

-- Relação N:N usuario x perfil
CREATE TABLE IF NOT EXISTS public.usuario_perfil (
                                                     perfil_id  BIGINT NOT NULL,
                                                     usuario_id BIGINT NOT NULL,
                                                     CONSTRAINT pk_usuario_perfil PRIMARY KEY (perfil_id, usuario_id),
    CONSTRAINT fk_usuper_on_perfil  FOREIGN KEY (perfil_id)  REFERENCES public.perfil (id),
    CONSTRAINT fk_usuper_on_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario (id)
);

-- Seeds de perfil (evita duplicar em reruns)
INSERT INTO public.perfil (descricao)
SELECT 'SUPER_ADMIN'
    WHERE NOT EXISTS (SELECT 1 FROM public.perfil WHERE descricao = 'SUPER_ADMIN');
