spring.application.name=agende-api

app.config.version=@project.version@
app.config.name=agende-api

# path
server.servlet.context-path=/agende-api
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maxLifetime=60000
spring.datasource.hikari.maximumPoolSize=40
spring.datasource.hikari.minimumIdle=1

spring.jpa.open-in-view=false

## Auditoria (envers)
spring.jpa.properties.hibernate.envers.audit_table_suffix=_aud
spring.jpa.properties.hibernate.envers.revision_field_name=rev
spring.jpa.properties.hibernate.envers.revision_type_field_name=revtype
spring.jpa.properties.hibernate.envers.global_with_modified_flag=true

## Token Secret
security.jwt.token.secret=PTwBbP2q74OvB8W04XK1hk7uR3e8fcCYDahKL4L1oOL67rXiVv5LHlQJDZczRtvo

## Configuracao Flyway
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false

spring.profiles.active=@APP_PROFILE@
